UPLOADED = "UPLOADED"
PROCESSING = "PROCESSING"
PROCESSED = "PROCESSED"
DO_NOT_PROCESS = "DO_NOT_PROCESS"
FAILED = "FAILED"
# Manual review statuses
REVIEW_PENDING = "PENDING"
REVIEW_APPROVED = "APPROVED"
REVIEW_REJECTED = "REJECTED"